blog/urls.py
from django.urls import path  

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserProfilePostListView, about

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='home-page'),
    path('post/<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/list/<username>/', UserProfilePostListView.as_view(), name='mark-user-home-page'),

    path('about/', about, name='about-page')
]

simple_blog/urls.py
from django.conf import settings  
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls')),
    path('users/', include('users.urls')),

    path('password-reset/', PasswordResetView.as_view(
            template_name='auth/password-reset.html'), 
                name="password-reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(
            template_name='auth/password-reset-done.html'), 
                name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
            template_name='auth/password-reset-confirm.html'), 
                name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
            template_name='auth/password-reset-complete.html'), 
                name="password_reset_complete"),

    path('tinymce/', include('tinymce.urls')),
    
    # path('ckeditor/', include('ckeditor_uploader.urls')),

    
]

if settings.DEBUG:
    urlpatterns += \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import user_register, request_user_profile, user_profile
from django.contrib.auth.views import LoginView, LogoutView 

app_name = 'users'

urlpatterns = [
    path('register/', user_register, name='user-register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='user-login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='user-logout'),
    path('profile/', request_user_profile, name='user-profile'),
    path('profile/detail/<username>', user_profile, name='indivisitual-profile-detail')
]

blog/models.py
from django.db import models
from django.urls  import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

from tinymce.models import HTMLField


class Post(models.Model):
    author          = models.ForeignKey(User, on_delete=models.CASCADE)
    title           = models.CharField(max_length=200)
    description     = HTMLField()
    is_draft        = models.BooleanField(default=True)
    create_date     = models.DateTimeField(auto_now_add=True)
    update_date     = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ["-create_date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={"pk": self.pk})

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from django import forms
from django.forms.utils import ErrorList
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User  
from django.db.models import Q
from .models import Post

# Post List view section
class PostListView(ListView):
    model = Post
    template_name = "blog/home_list.html"
    context_object_name = 'queryset'
    ordering = ["-create_date"]

    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        qs = Post.objects.all()
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(author__username__iexact = query)|
                Q(description__icontains = query)|
                Q(title__icontains=query))
        return qs


# Indivitusual user's post list view section
class UserProfilePostListView(ListView):
    model = Post  
    template_name = "blog/user_post_list.html"
    ordering = ["-create_date"]
    context_object_name = "queryset"

    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        qs = Post.objects.filter(author=user, is_draft=False)
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(
                Q(author__username__iexact = query)|
                Q(description__icontains = query)|
                Q(title__icontains=query))
        return qs


# Post detail view section
class PostDetailView(DetailView):
    model = Post 
    template_name = "blog/post_detail.html"
    context_object_name = 'object'


# New Post Create view section
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post  
    template_name = 'blog/post_create.html'
    fields = ["title", "description"]
    
    def form_valid(self,form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
            return super(PostCreateView, self).form_valid(form)
        else:
            form._errors[forms.forms.NON_FIELD_ERRORS] = ErrorList(['User must be login to coutinue!'])
            return self.form_invalid(form)


# Post Edit view section
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post  
    template_name = 'blog/post_create.html'
    fields = ["title", "description"]

    # def form_valid(self, form):
    #     if form.instance.author == self.request.user:
    #         return super(PostUpdateView, self).form_valid(form)
    #     else:
    #         form.errors[forms.forms.NON_FIELD_ERRORS]=ErrorList(['You are not instance user:)'])
    #         return self.form_invalid(form)

    # insted of ---->

    # request.user === post.author section
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False




# Delete Post view section
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post  
    template_name = 'blog/delete_confirm.html'
    success_url = "/"

    # request.user === post.author
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False



# about section view section
def about(request):
    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}{{ block.super }}-About{% endblock title %}
{% block content %}

{% static 'static/image/about.jpg' as img %} 

<!-- 
    ######################## ABOUT SECTION #########################
 -->

<div class="container">
  <h2 style="text-align:center;" class="text-muted">About Us</h2><br>

  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus imperdiet felis ut commodo rhoncus. Ut
    sollicitudin ex in quam feugiat tempus. Quisque non lacus facilisis, molestie sapien vitae, auctor ante. Ut finibus
    sollicitudin ante id elementum. Nulla turpis lorem, facilisis a consectetur ac, hendrerit sed ligula. Praesent ac
    mauris interdum, commodo dolor vitae, convallis erat. Ut ante elit, placerat nec lacinia ut, eleifend eget velit.
    Phasellus vel enim sagittis turpis faucibus luctus ut scelerisque justo. Nulla luctus cursus orci non auctor. Nullam
    a enim consequat, sagittis eros eget, accumsan turpis. Maecenas efficitur mollis nunc, ornare venenatis augue
    dignissim at. Phasellus feugiat odio eget dui vulputate viverra. Ut felis sapien, mattis id sem nec, cursus
    imperdiet tellus. Sed iaculis est turpis, vitae ullamcorper lorem consequat vitae.

    vehicula. Mauris tempus lorem nec convallis tempus. Donec malesuada tristique nulla. Suspendisse potenti. Donec
    felis urna, dapibus ut placerat a, mattis id orci. Etiam ultricies sed est a viverra. Duis venenatis sit amet nunc a
    feugiat. Donec vestibulum dui in pellentesque finibus.</p>
</div>
{% endblock content %}

blog/templates/blog/delete_confirm.html
{% extends "base.html" %}
{% block title %}{{ block.super }}-Post-Create{% endblock title %}
{% block content %}

<!-- 
    ######################## POST DELETE CONFIRM #########################
 -->

<div class="content-section">
    <div class="card">
        <div class="card-body">
            <h4>Are Confirm to delete "{{ object.title }}"</h4>
            <form action="" method="POST">
                {% csrf_token %}
                <button class="btn btn-outline-danger" type="submit">Confirm</button>
                <a href="{% url 'blog:post-detail' pk=object.pk %}" class="btn btn-primary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/home_list.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-Home{% endblock title %}
{% load thumbnail %}
{% block content %}

<!-- 
    ######################## POST LIST #########################
 -->


<div class="content">
    {% if request.GET.q %}
    <div class="alert alert-info">
        Result for: <b>{{ request.GET.q }}</b>
    </div>
    {% endif %}
    {% for post in queryset %}
    <div class="card" style="width: 60rem;">
        <span class="mt-2 ml-1 border-bottom">
            {% thumbnail post.author.userprofile.image "30x30" crop="center" as im %}
            <a class="btn btn-link" href="{% url 'users:indivisitual-profile-detail' username=post.author.username %}">
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="rounded-circle">
            </a>
            {% endthumbnail %}
            <a href="{% url 'blog:mark-user-home-page' username=post.author.username %}">@{{ post.author }}</a>
            <small class="text-muted">{{ post.create_date }}</small>
        </span>
        <div class="card-body">

            <a href="{% url 'blog:post-detail' pk=post.pk %}">
                <span style="font-size: 30px; color:black;">{{ post.title }}</span>
            </a>

            <p>{{ post.description|truncatewords:30|safe }}</p>
        </div>
    </div><br>
    {% empty %}
    <p>Not Found!</p>
    {% endfor %}



    <!-- PAGINATOR -->
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page }}">Previoue</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:"-3" and  num < page_obj.number|add:"3" %}
    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}

</div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}-Post-Create{% endblock title %}
{% block content %}

<!-- 
    ######################## POST CREATE SECTION #########################
 -->


<div class="content-section">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Blog Post</legend>
                    {{ form|crispy}}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-Post-Detail{% endblock title %}
{% load thumbnail %}
{% block content %}

<!-- 
    ######################## POST DETAIL SECTION #########################
 -->

<div class="content">

    <div id="#post-detail">
        <div class="card" style="width: 60rem;">
            <span class="mt-2 ml-1 airticle-metadata border-bottom">
                {% thumbnail object.author.userprofile.image "40x40" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="rounded-circle">
                {% endthumbnail %}
                <a href="{% url 'blog:mark-user-home-page' username=object.author.username %}">@{{ object.author }}</a>
                <small class="text-muted">{{ object.create_date }}</small>
            </span>
            <div class="card-body">
                <span style="font-size: 30px;">{{ object.title }}</span>
                {% if object.author == request.user %}
                <a href="{% url 'blog:post-delete' pk=object.pk %}" class="ml-5  btn-danger btn-sm">Delete</a>
                <a href="{% url 'blog:post-update' pk=object.pk %}" class="ml-1  btn-secondary btn-sm">Update</a>
                {% endif %}<br><br>
                <p>{{ object.description|safe }}</p><br>
            </div>
        </div>

    </div><br>

    <!-- Discus comment system -->
    <div id="discus-comment">
        <div class="card" style="width: 60rem;">
            <div class="card-body">
                <div id="disqus_thread"></div>
                <script>

                    /**
                    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                    /*
                    var disqus_config = function () {
                    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };
                    */
                    (function () { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = 'https://mahmudsajib.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                        powered
                        by Disqus.</a></noscript>
            </div>
        </div>

    </div>

</div>


{% endblock content %}

blog/templates/blog/user_post_list.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-Home{% endblock title %}
{% load thumbnail %}
{% block content %}
<div class="content">
    {% if request.GET.q %}
    <div class="alert alert-info">
        Result for: <b>{{ request.GET.q }}</b>
    </div>
    {% endif %}
    <div class="text-center mb-2" style="font-size:30px;color:green;">{{ view.kwargs.username }}
        <small>({{ page_obj.paginator.count }})</small>
    </div>

    {% for post in queryset %}
    <div class="card" style="width: 60rem;">
        <span class="mt-2 ml-1 border-bottom">
            {% thumbnail post.author.userprofile.image "30x30" crop="center" as im %}
            <a class='btn btn-link' href="{% url 'users:indivisitual-profile-detail' username=post.author.username %}"
                title='You can see profile!'>
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="rounded-circle">
            </a>
            {% endthumbnail %}
            <a href="{% url 'blog:mark-user-home-page' username=post.author.username %}"
                title="You can see all post">@{{ post.author }}</a>
            <small class="text-muted">{{ post.create_date }}</small>
        </span>
        <div class="card-body">

            <a href="{% url 'blog:post-detail' pk=post.pk %}">
                <span style="font-size: 30px; color:black;">{{ post.title }}</span>
            </a>

            <p>{{ post.description|truncatewords:30|safe }}</p>
        </div>
    </div><br>
    {% endfor %}

    <!-- Post list paginator -->
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page }}">Previoue</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:"-3" and  num < page_obj.number|add:"3" %}
    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}

</div>
{% endblock content %}