blog/urls.py
from django.urls import path  

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserProfilePostListView, about

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='home-page'),
    path('post/<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/list/<username>/', UserProfilePostListView.as_view(), name='mark-user-home-page'),

    path('about/', about, name='about-page')
]

simple_blog/urls.py
from django.conf import settings  
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls')),
    path('users/', include('users.urls')),

    path('password-reset/', PasswordResetView.as_view(
            template_name='auth/password-reset.html'), 
                name="password-reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(
            template_name='auth/password-reset-done.html'), 
                name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
            template_name='auth/password-reset-confirm.html'), 
                name="password_reset_confirm"),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
            template_name='auth/password-reset-complete.html'), 
                name="password_reset_complete"),

    path('tinymce/', include('tinymce.urls')),
    
    # path('ckeditor/', include('ckeditor_uploader.urls')),

    
]

if settings.DEBUG:
    urlpatterns += \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import user_register, request_user_profile, user_profile
from django.contrib.auth.views import LoginView, LogoutView 

app_name = 'users'

urlpatterns = [
    path('register/', user_register, name='user-register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='user-login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='user-logout'),
    path('profile/', request_user_profile, name='user-profile'),
    path('profile/detail/<username>', user_profile, name='indivisitual-profile-detail')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- title -->
    <title>{% block title %}Django{% endblock title %}</title>

    <!--======Tinymce Text-Editor=========-->
    <script src="{% static 'static/js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'static/js/tinymce/custom.js' %}"></script>

    <!-- bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container mt-2">

        <!-- content -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            <strong>Success!</strong>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}{% endblock content %}


        <!-- side bar -->
        <!-- <div class="col-md-4">
                <div class="card" style="width: 18rem; position: sticky; top: 55px;">
                    <div class="card-body">
                        <h3>Our Sidebar</h3>
                        <p>You can put any information here..</p>
                    </div>
                    <ul class="list-group list-group-flush" style="margin: 0 10px 0 10px;">
                        <li class="list-group-item">Latest post</li>
                        <li class="list-group-item">Annoucement</li>
                        <li class="list-group-item">Calender</li>
                    </ul>
                </div>

            </div> -->
    </div>



    <!-- bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light py-1 sticky-top" style="background-color: #3D1E5B;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" style="color:white;" href="{% url 'blog:home-page' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:white;" href="{% url 'blog:about-page' %}">About</a>
        </li>
      </ul>
      <ul class="nav navbar-nav">

        {% if request.user.is_authenticated %}

        <div class="dropdown">
            <button class="btn bt-default  dropdown-toggle" style='color:white;' type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <a class="dropdown-item"  href="{% url 'blog:post-create' %}">New Post</a>
              <a class="dropdown-item"  href="{% url 'users:user-profile' %}">settings</a>
              <a class="dropdown-item"  href="{% url 'users:user-logout' %}">Logout</a>
            </div>
          </div>
        {% else %}
          <li class="nav-item">
              <a class="nav-link" style="color:white;" href="{% url 'users:user-login' %}">Login</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" style="color:white;" href="{% url 'users:user-register' %}">Register</a>
          </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" value="{{ request.GET.q }}">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>